### ISSUE TITLE
Any ideas on using hookFor?

### ISSUE THREAD

**Issue by Hypercubed** [jozefizso/generator-license#3] opened 2013-09-09 02:46 UTC
This generator is nice.  I'd like to include it in my generator (https://github.com/Hypercubed/generator-commander).  I can use the hookFor and peerDependencies to run generator-license from generator-commander but it will ask again for the author name (that I am pulling from github) and license.  Is there a way to skip these prompts when using hookFor?  One option is to accept an author name and license from the command line arguments in generator-license.

This seams line a common potential use for generator-license. Any ideas?

**Comment by SBoudrias** [comment] 2015-11-14 01:21
Hey, this is still an issue today.

This is because the code is doing simple truthy checks `!this.options.foo`. The issue is that a user might already have provided an empty value in a previous generator.

I think it'd be better if we did checks for `this.options.foo == null`, so we'd know if we've just been passed an empty value.

**Comment by iamstarkov** [comment] 2016-01-27 00:05
is it fixed after merged #20?

**Closed** 2017-01-08 21:55 UTC
Labels: question
